pipeline {
    agent any

    stages {
        stage("Merge to Main") {
            steps {
                withCredentials([usernamePassword(credentialsId: '82fecaa5-889b-4d66-b0ae-f3f0c998438c', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')])
                script {
                    sh "git checkout main"
                    sh "git merge origin/dev"
                    sh "git push origin main"
                }
            }
        }
    }
}

