pipeline {
    agent any

    stages {
        stage("Merge to Main") {
            steps {
                script {
                    git branch: 'main',
                    credentialsId: '82fecaa5-889b-4d66-b0ae-f3f0c998438c',
                    url: 'https://github.com/Norbert00/rectangle_area_calculator_CI_CD_process.git'
                    sh 'git merge dev'
                    sh 'git push origin main'
                }
            }
        }
    }
}

