pipeline {
    agent any

    stages {
        stage("Merge to Main") {
            steps {
                script {
                    sh "git checkout main"
                    sh "git merge dev"
                    sh "git push origin main"
                }
            }
        }
    }
}

